### ISSUE TITLE
Error on Installation of Katuali

### ISSUE THREAD

**Issue by ghost** [nanoporetech/katuali#2]
Hi,

I am trying to install Katuali. I already have snakemake installed but on running the command "make install" to run the makefile I get the following error below in the last 10 lines on the installation script.
May you please assist me?

ERROR RECEIVED IN LAST 10 LINES OF INSTALLATION SCRIPT:

**Writing /tmp/easy_install-0uhyrzri/datrie-0.7.1/setup.cfg
Running datrie-0.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0uhyrzri/datrie-0.7.1/egg-dist-tmp-jo41x002
warning: no files found matching 'tests/words100k.txt.zip'
src/datrie.c:4:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:22: recipe for target 'install' failed
make: *** [install] Error 1**

**Comment by cjw85** [comment]
Hi @DuncanTN,

Thank you for trying katuali. The error indicates that one of snakemake's dependencies (datrie) cannot be compiled (there's a related issue here: [Issue #934](https://bitbucket.org/snakemake/snakemake/issues/934/installation-failed-in-python-37)).

Can I ask what operating system you are using? You will need to install the python development package to get this to work.

**Comment by ghost** [comment]
I am using Ubuntu 18.04
 I have resolved the issue now and  you are right. I need to install the python3-dev package. I  am now working on installing the tools that Katuali uses but cannot locate Guppy on Github. Can you please help with locating the tool guppy?

**Comment by cjw85** [comment]
Guppy download links are available from the [Nanopore Community](https://community.nanoporetech.com/downloads) site.

If you have already basecalls, guppy (or any other basecaller) is not required to run katuali workflows, the documentation as details on how to [start from existing basecalls](https://nanoporetech.github.io/katuali/examples.html#starting-from-existing-basecalls).

**Comment by ghost** [comment]
Ok thank you very much
