### ISSUE TITLE
Make install failed

### ISSUE THREAD

**Issue by Kata-Pa** [nanoporetech/katuali#6]
Hello!

I am working on Ubuntu 16.04.6 and I get an error when I run make install:

test -d venv || virtualenv venv --prompt '(katuali) ' --python=python3
/bin/sh: 1: virtualenv: not found
Makefile:17: recipe for target 'venv/bin/activate' failed
make: *** [venv/bin/activate] Error 127

Any hint what is wrong?

Thank you!
/Katerina

**Comment by javierblasco** [comment]
Hi @Kata-Pa, 

One of the requirements for medaka in Ubuntu is virtualenv (`python-virtualenv`). Your error seems to indicate you don't have it installed in your system. If you install it, the problem should go away.

**Comment by javierblasco** [comment]
Hello @Kata-Pa, 

The problem is that you don't have virtualenv (`python-virtualenv`). If you install it, the installation should work.  Thank you for reporting this, I will update the documentation to make this more clear in the future.

**Comment by Kata-Pa** [comment]
Ah ok, I am sorry I didnt pay more attention to the error description.

Thank you!
/Katerina
